# dev environment running on github configs repository
server:
  port: 7071
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/eroscupid88/nomosnow-config-repository
          searchPaths: gateway-server*,sport-event-configuration*,eureka-server*,sport-organization-configuration*,event-request-configuration*




management:
  endpoints:
    web:
      exposure:
        include: '*'